### PR TITLE
paco with opam

### PR DESCRIPTION
**Pull request by minkiminki**

### CODE REVIEW

**Review by jeehoonkang — APPROVED** [review]
Supernice!

**Comment by jeehoonkang** [comment]
Btw, I'd appreciate if we could set a (Travis) CI for this repo, too.

**Comment by minkiminki** [comment]
@jeehoonkang I'll try it.

**Comment by minkiminki** [comment]
I added travis CI and tested [it](https://github.com/minkiminki/promising-coq/runs/78011420).

**Pull request merged**
